### ISSUE TITLE
White screen on start

### ISSUE THREAD

**Issue by VideoMakerGuy** [pamods/pamm-atom#10]
Hello, I don't know what the issue is but whenever I first installed PA Mod Manager it worked perfectly fine. I installed 3 mods. Next time I try to use it, it white screens on me. Now I thought like any normal human being that it was one of the mods I installed. well I have reinstalled PA Mod manager countless times and have reinstalled PA itself and am still at a loss with it. Please help, I need the mod manager for the upcoming tournament. Thanks.

**Comment by mereth** [comment]
PAMM will now disable the auto resize after a crash.
