### ISSUE TITLE
PA No longer launches

### ISSUE THREAD

**Issue by nizzan** [pamods/pamm-atom#11]
I noticed an update today when i opened PAMM, and my PA is no longer launching at all when i try to use PAMM.
PA still launches from steam just fine.
My Event Viewer on my computer shows no errors related to this.

Any advice?

**Comment by johansigfrids** [comment]
I am seeing the same problem after the 1.0.2 update.

**Comment by mereth** [comment]
Is it fixed since 1.0.3 ?

**Comment by nizzan** [comment]
Just tried it, and yes it seems to work as of right now with the new version.
Thanks.
- Nizzan
