### ISSUE TITLE
Wont work

### ISSUE THREAD

**Issue by thatsonofabroom** [pamods/pamm-atom#13]
It keeps asking to type in password but which one?

**Comment by mereth** [comment]
The only password PAMM may ask, it's when you click on the login link in the top right corner if you don't use the steam release. It's the uberent login/password account. Nothing mandatory.

If not this one, I have no idea of what you are talking about.

**Comment by thatsonofabroom** [comment]
thanks for help =D

**Comment by thatsonofabroom** [comment]
Still won't work. it just says "password is inccorect

**Comment by thatsonofabroom** [comment]
This issue has been fixed it was the file opener that was asking for password not pamm
