### ISSUE TITLE
Show mod icons on "UI Mods" and "Server Mods" tabs for easier recognition

### ISSUE THREAD

**Issue by nhooey** [pamods/pamm-atom#24]
A picture is worth a thousand words.

Why not show the mod icons on the installed mods tabs?

**Comment by mereth** [comment]
You can use the "Show Icon" option in the settings tab (the 'gear' icon).

**Comment by nhooey** [comment]
It's probably best to have these on by default, so your mind doesn't have to track two different appearances for the same entity.
