### ISSUE TITLE
Installation Error 2349

### ISSUE THREAD

**Issue by corppneq** [pamods/pamm-atom#9]
I get an error when I'm trying to install the mod manager:

> The installer has encountered an unexpected errer installing this package. This may indicate a problem with this package. The error code is 2349.

**Comment by corppneq** [comment]
That worked.
The update mechanism the mod manager offers works, right?
I don't have to pull the newest changes unless I want to reinstall the mod manager, right?
And the mod manager does not uses anything in the local repo after installation, so that I can delete the repo?

**Comment by mereth** [comment]
that's right
